/* Generated by the Nim Compiler v2.2.2 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI553648334 = {size: 0, kind: 16, base: null, node: null, finalizer: null};
var NTI553648134 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI553648167 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554445 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI553648132 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI553648135 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI553648133 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI553648136 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI553648131 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555175 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555174 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555172 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555172 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555172.node = NNI33555172;
NTI33555174.base = NTI33555171;
NTI33555175.base = NTI33555171;
var NNI33555171 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555174, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555175, name: "up", sons: null}]};
NTI33555171.node = NNI33555171;
var NNI33555167 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555167.node = NNI33555167;
NTI33555171.base = NTI33555167;
NTI33555172.base = NTI33555171;
NTI134217741.base = NTI33555172;
NTI134217743.base = NTI134217741;
var NNI553648131 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}]};
NTI553648131.node = NNI553648131;
var NNI553648132 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554445, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554445, name: "Field1", sons: null}]};
NTI553648132.node = NNI553648132;
var NNI553648135 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI553648132, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI553648132, name: "Field1", sons: null}]};
NTI553648135.node = NNI553648135;
var NNI553648133 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "strRepr", len: 0, typ: NTI33554450, name: "strRepr", sons: null}, 
{kind: 1, offset: "requisitos", len: 0, typ: NTI553648135, name: "requisitos", sons: null}]};
NTI553648133.node = NNI553648133;
var NNI553648136 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "bioma", len: 0, typ: NTI553648133, name: "bioma", sons: null}, 
{kind: 1, offset: "coordenada", len: 0, typ: NTI553648131, name: "coordenada", sons: null}]};
NTI553648136.node = NNI553648136;
var NNI553648167 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI553648136, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554466, name: "Field1", sons: null}]};
NTI553648167.node = NNI553648167;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555172;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555172;
var NNI553648134 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554445, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554445, name: "Field1", sons: null}]};
NTI553648134.node = NNI553648134;
NTI553648334.base = NTI33554450;

function toJSStr(s_p0) {
  var result_33556910 = null;

    var res_33556964 = newSeq__system_u2507((s_p0).length);
    var i_33556965 = 0;
    var j_33556966 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556965 < (s_p0).length)) break Label2;
          var c_33556967 = s_p0[i_33556965];
          if ((c_33556967 < 128)) {
          res_33556964[j_33556966] = String.fromCharCode(c_33556967);
          i_33556965 += 1;
          }
          else {
            var helper_33556993 = newSeq__system_u2507(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556994 = c_33556967.toString(16);
                  if ((((code_33556994) == null ? 0 : (code_33556994).length) == 1)) {
                  helper_33556993.push("%0");;
                  }
                  else {
                  helper_33556993.push("%");;
                  }
                  
                  helper_33556993.push(code_33556994);;
                  i_33556965 += 1;
                  if ((((s_p0).length <= i_33556965) || (s_p0[i_33556965] < 128))) {
                  break Label3;
                  }
                  
                  c_33556967 = s_p0[i_33556965];
                }
            };
++excHandler;
            try {
            res_33556964[j_33556966] = decodeURIComponent(helper_33556993.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556964[j_33556966] = helper_33556993.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556966 += 1;
        }
    };
    if (res_33556964.length < j_33556966) { for (var i = res_33556964.length ; i < j_33556966 ; ++i) res_33556964.push(null); }
               else { res_33556964.length = j_33556966; };
    result_33556910 = res_33556964.join("");

  return result_33556910;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    throw e_p0;

  
}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557321 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2869(ti_p2))) {
      result_33557321 = src_p1;
      }
      else {
        result_33557321 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557321 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557321 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557321 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557321 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557321, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557321 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557321 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557321 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557321[i] = nimCopy(result_33557321[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557321 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557321 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557321[i] = nimCopy(result_33557321[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557321 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557321 = src_p1;
      break;
    }

  return result_33557321;

}
                  var biomas_553648174 = [{strRepr: "Floresta", requisitos: {Field0: {Field0: 0.4, Field1: 0.8}, Field1: {Field0: 0.6, Field1: 1.0}}}, {strRepr: "Deserto", requisitos: {Field0: {Field0: 0.7, Field1: 1.0}, Field1: {Field0: 0.0, Field1: 0.4}}}, {strRepr: "Geleira", requisitos: {Field0: {Field0: 0.0, Field1: 0.3}, Field1: {Field0: 0.6, Field1: 1.0}}}, {strRepr: "Planalto", requisitos: {Field0: {Field0: 0.4, Field1: 0.7}, Field1: {Field0: 0.0, Field1: 0.4}}}, {strRepr: "Pântano", requisitos: {Field0: {Field0: 0.3, Field1: 0.6}, Field1: {Field0: 0.4, Field1: 0.8}}}, {strRepr: "FlorestaTropical", requisitos: {Field0: {Field0: 0.6, Field1: 1.0}, Field1: {Field0: 0.8, Field1: 1.0}}}];

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557361 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557361 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557361;

}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557356 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557356 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557356;

}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}
var objectID_771752114 = [0];

function add__system_u1942(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function newSeq__system_u2507(len_p0) {
  var result_33556943 = [];

    result_33556943 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556943[i] = null; }
  return result_33556943;

}

function unhandledException(e_p0) {
    var buf_33556658 = [[]];
    if (!(((e_p0.message).length == 0))) {
    buf_33556658[0].push.apply(buf_33556658[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556658[0].push.apply(buf_33556658[0], e_p0.message);;
    }
    else {
    buf_33556658[0].push.apply(buf_33556658[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556658[0].push.apply(buf_33556658[0], [32,91]);;
    add__system_u1942(buf_33556658, 0, e_p0.name);
    buf_33556658[0].push.apply(buf_33556658[0], [93,10]);;
    var cbuf_33556659 = toJSStr(buf_33556658[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556659);
  }
  else {
    throw cbuf_33556659;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function isFatPointer__system_u2869(ti_p0) {
  var result_33557303 = false;

  BeforeRet: {
    result_33557303 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557303;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function HEX24__main_u47(coord_p0) {
  var result_553648177 = null;

    result_553648177 = (((("(" + (coord_p0.Field0).toString()) + ",") + (coord_p0.Field1).toString()) + ")");

  return result_553648177;

}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

    var old_301990096 = (result_p0[result_p0_Idx]).length;
    if (result_p0[result_p0_Idx].length < (Temporary1 = chckRange(addInt(old_301990096, n_p3), 0, 2147483647), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_301990110 = 0;
      var i_553648539 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_553648539 < n_p3)) break Label4;
            iHEX60gensym4_301990110 = i_553648539;
            result_p0[result_p0_Idx][chckIndx(addInt(old_301990096, iHEX60gensym4_301990110), 0, (result_p0[result_p0_Idx]).length - 1)] = x_p1.charCodeAt(chckIndx(addInt(start_p2, iHEX60gensym4_301990110), 0, (x_p1).length - 1));
            i_553648539 = addInt(i_553648539, 1);
          }
      };
    };

  
}

function addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u202(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));

  
}

function addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, x_p1) {
    addChars__stdZprivateZdigitsutils_u198(result_p0, result_p0_Idx, ((x_p1) + ""));

  
}

function addInt__stdZprivateZdigitsutils_u241(result_p0, result_p0_Idx, x_p1) {
    addInt__stdZprivateZdigitsutils_u223(result_p0, result_p0_Idx, BigInt(x_p1));

  
}

function HEX24__systemZdollars_u8(x_p0) {
  var result_385875978 = [[]];

    result_385875978[0] = nimCopy(null, [], NTI33554449);
    addInt__stdZprivateZdigitsutils_u241(result_385875978, 0, x_p0);

  return result_385875978[0];

}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32]).concat(HEX24__systemZdollars_u8(i_p0),[32,110,111,116,32,105,110,32],HEX24__systemZdollars_u8(a_p1),[32,46,46,32],HEX24__systemZdollars_u8(b_p2));
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function comporta__main_u50(tupla_p0, valor_p1) {
  var result_553648181 = false;

  BeforeRet: {
    result_553648181 = ((valor_p1 < tupla_p0.Field1) && (tupla_p0.Field0 <= valor_p1));
    break BeforeRet;
  };

  return result_553648181;

}

function comporta__main_u54(bioma_p0, caracteristica_p1) {
  var result_553648185 = false;

  BeforeRet: {
    result_553648185 = (comporta__main_u50(bioma_p0.requisitos.Field0, caracteristica_p1.Field0) && comporta__main_u50(bioma_p0.requisitos.Field1, caracteristica_p1.Field1));
    break BeforeRet;
  };

  return result_553648185;

}

function coord2bioma__main_u58(coord_p0) {
  var result_553648188 = {Field0: ({bioma: ({strRepr: null, requisitos: {Field0: {Field0: 0.0, Field1: 0.0}, Field1: {Field0: 0.0, Field1: 0.0}}}), coordenada: {Field0: 0, Field1: 0}}), Field1: false};

  BeforeRet: {
    if (globalThis.coordBiomaCache_553648220 === undefined) {
      globalThis.coordBiomaCache_553648220 = {};
    }
    var offsetadaCoord_553648221 = nimCopy(null, {Field0: addInt(coord_p0.Field0, 40), Field1: addInt(coord_p0.Field1, 40)}, NTI553648131);
    var posRaioDaCoordenada_553648222 = {Field0: Math.floor(offsetadaCoord_553648221.Field0/80), Field1: Math.floor(offsetadaCoord_553648221.Field1/80)};
    if (!((coordBiomaCache_553648220[HEX24__main_u47(posRaioDaCoordenada_553648222)] === undefined))) {
    var colontmp__553648524 = nimCopy(null, coordBiomaCache_553648220[HEX24__main_u47(posRaioDaCoordenada_553648222)]["Field1"], NTI553648136);
    var colontmp__553648525 = false;
    result_553648188 = nimCopy(result_553648188, {Field0: nimCopy(null, colontmp__553648524, NTI553648136), Field1: colontmp__553648525}, NTI553648167);
    break BeforeRet;
    }
    
    Label1: {
        Label2: while (true) {
        if (!true) break Label2;
          var caracteristicaBiomaAleatoria_553648250 = {Field0: Math.random(), Field1: Math.random()};
          Label3: {
            var bioma_553648293 = ({strRepr: null, requisitos: {Field0: {Field0: 0.0, Field1: 0.0}, Field1: {Field0: 0.0, Field1: 0.0}}});
            var i_553648531 = 0;
            Label4: {
                Label5: while (true) {
                if (!true) break Label5;
                  bioma_553648293 = nimCopy(bioma_553648293, biomas_553648174[chckIndx(i_553648531, 0, (biomas_553648174).length - 1)], NTI553648133);
                  if (comporta__main_u54(bioma_553648293, caracteristicaBiomaAleatoria_553648250)) {
                  var raio_553648294 = {bioma: nimCopy(null, bioma_553648293, NTI553648133), coordenada: nimCopy(null, posRaioDaCoordenada_553648222, NTI553648131)};
                  coordBiomaCache_553648220[HEX24__main_u47(posRaioDaCoordenada_553648222)] = {Field0: nimCopy(null, caracteristicaBiomaAleatoria_553648250, NTI553648134), Field1: nimCopy(null, raio_553648294, NTI553648136)};
                  var colontmp__553648528 = nimCopy(null, raio_553648294, NTI553648136);
                  var colontmp__553648529 = true;
                  result_553648188 = nimCopy(result_553648188, {Field0: nimCopy(null, colontmp__553648528, NTI553648136), Field1: colontmp__553648529}, NTI553648167);
                  break BeforeRet;
                  }
                  
                  if ((5 <= i_553648531)) {
                  break Label4;
                  }
                  
                  i_553648531 += 1;
                }
            };
          };
        }
    };
  };

  return result_553648188;

}

function andar(quant_p0, direHEXC3HEXA7HEXC3HEXA3o_p1) {
    var Temporary1;

  var result_553648467 = [null, null];

  BeforeRet: {
    switch (direHEXC3HEXA7HEXC3HEXA3o_p1) {
    case "cima":
      personagem_553648463[0].Field1 = subInt(personagem_553648463[0].Field1, quant_p0);
      break;
    case "baixo":
      personagem_553648463[0].Field1 = addInt(personagem_553648463[0].Field1, quant_p0);
      break;
    case "esquerda":
      personagem_553648463[0].Field0 = subInt(personagem_553648463[0].Field0, quant_p0);
      break;
    case "direita":
      personagem_553648463[0].Field0 = addInt(personagem_553648463[0].Field0, quant_p0);
      break;
    default: 
      break;
    }
    var tmpTuple_553648484 = coord2bioma__main_u58(personagem_553648463[0]);
    var raioAtual_553648485 = nimCopy(null, tmpTuple_553648484["Field0"], NTI553648136);
    var ehNovo_553648486 = tmpTuple_553648484["Field1"];
    if (ehNovo_553648486) {
    Temporary1 = ((("Novo raio - " + raioAtual_553648485.bioma.strRepr) + " - ") + HEX24__main_u47(raioAtual_553648485.coordenada));
    }
    else {
    Temporary1 = "";
    }
    
    var mensagemBiomaNovo_553648487 = Temporary1;
    var mensagemLogAndar_553648488 = ((("Mov - " + HEX24__main_u47(personagem_553648463[0])) + " - ") + raioAtual_553648485.bioma.strRepr);
    result_553648467 = nimCopy(result_553648467, [mensagemLogAndar_553648488, mensagemBiomaNovo_553648487], NTI553648334);
    break BeforeRet;
  };

  return result_553648467;

}
var personagem_553648463 = [{Field0: 0, Field1: 0}];
(coord2bioma__main_u58(personagem_553648463[0]));
